name: automerge 
 on: 
   pull_request: 
     types: 
       - labeled 
       - unlabeled 
       - synchronize 
       - opened 
       - edited 
       - ready_for_review 
       - reopened 
       - unlocked 
   pull_request_review: 
     types: 
       - submitted 
   check_suite: 
     types: 
       - completed 
   status: {} 
 jobs: 
   automerge: 
     runs-on: ubuntu-latest 
     steps: 
       - id: automerge 
         name: automerge 
         uses: "pascalgn/automerge-action@v0.15.3" 
         env: 
           GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
           MERGE_LABELS: "documentation"
           MERGE_REMOVE_LABELS: ""
           MERGE_METHOD: "merge"
           MERGE_COMMIT_MESSAGE: "pull-request-description"
           MERGE_FILTER_AUTHOR: "ImgBotApp"
           MERGE_FORKS: "false"
           MERGE_RETRIES: "6"
           MERGE_RETRY_SLEEP: "10000"
           MERGE_REQUIRED_APPROVALS: "0"
           UPDATE_LABELS: ""
           UPDATE_METHOD: "merge"
           PULL_REQUEST: ""
           BASE_BRANCHES: "main"
